### ISSUE TITLE
PieChart example makes app crash

### ISSUE THREAD

**Issue by fxhereng** [wuxudong/react-native-charts-wrapper#105]
### Version

RN - 0.47.1
chartswrapper: 0.2.10
Platform: Android

### Code (example copy paste)

```javascript
export default class PowenPieChart extends Component {

	constructor(props) {
    super(props);

    this.state = {
      legend: {
        enabled: true,
        textSize: 8,
        form: 'CIRCLE',
        position: 'RIGHT_OF_CHART',
        wordWrapEnabled: true
      },
      data: {
        dataSets: [{
          values: [{value: 40, label: 'Sandwiches'},
            {value: 21, label: 'Salads'},
            {value: 15, label: 'Soup'},
            {value: 9, label: 'Beverages'},
            {value: 15, label: 'Desserts'}],
          label: 'Pie dataset',
          config: {
            colors: [processColor('#C0FF8C'), processColor('#FFF78C'), processColor('#FFD08C'), processColor('#8CEAFF'), processColor('#FF8C9D')],
            valueTextSize: 20,
            valueTextColor: processColor('green'),
            sliceSpace: 5,
            selectionShift: 13
          }
        }],
      },
      description: {
        text: 'This is Pie chart description',
        textSize: 15,
        textColor: processColor('darkgray'),

      }
		};
  }

  static defaultProps = {
    ...Component.defaultProps,
  }

  handleSelect(event) {
    let entry = event.nativeEvent;
    if (entry == null) {
      this.setState({...this.state, selectedEntry: null});
    } else {
      this.setState({...this.state, selectedEntry: JSON.stringify(entry)});
    }
  }

  render() {
    return (

      <View style={{flex: 1}}>

        <View style={{height:80}}>
          <Text> selected entry</Text>
          <Text> {this.state.selectedEntry}</Text>
        </View>

        <View style={styles.container}>
          <PieChart
            style={styles.chart}
            logEnabled={true}
            chartBackgroundColor={processColor('pink')}
            chartDescription={this.state.description}
            data={this.state.data}
            legend={this.state.legend}
            entryLabelColor = {processColor('black')}
            entryLabelTextSize = {20}                 
            rotationEnabled={false}
            drawSliceText={true}
            usePercentValues={false}
            centerText={'Pie center text!'}
            centerTextRadiusPercent={100}
            holeRadius={40}
            holeColor={processColor('#f0f0f0')}
            transparentCircleRadius={45}
            transparentCircleColor={processColor('#f0f0f088')}
            maxAngle={350}
            onSelect={this.handleSelect.bind(this)}/>
        </View>

      </View>
    );
	}
}



const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  chart: {
    flex: 1
  }
});
```

### Crash
```
08-22 12:12:54.015 11203-11203/com.powen_app I/MPAndroidChart: offsetLeft: 0.0, offsetTop: 0.0, offsetRight: 0.0, offsetBottom: 0.0
08-22 12:12:54.093 11203-11203/com.powen_app I/MPAndroidChart: offsetLeft: 0.0, offsetTop: 0.0, offsetRight: 0.0, offsetBottom: 0.0
08-22 12:12:54.096 11203-11203/com.powen_app E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.powen_app, PID: 11203
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.Reference.get()' on a null object reference
                                                                   at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:638)
                                                                   at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:131)
                                                                   at android.view.View.draw(View.java:17242)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16207)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.View.draw(View.java:17008)
                                                                   at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                   at android.view.View.draw(View.java:17245)
                                                                   at android.widget.ScrollView.draw(ScrollView.java:1759)
                                                                   at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:334)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16207)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3758)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3738)
                                                                   at android.view.View.updateDisplayListIfDirty(View.java:16170)
                                                                   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:677)
                                                                   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:683)
                                                                   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:797)
                                                                   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2991)
                                                                   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2785)
08-22 12:12:54.096 11203-11203/com.powen_app E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2376)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6768)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                                   at android.os.Handler.handleCallback(Handler.java:761)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                   at android.os.Looper.loop(Looper.java:156)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6577)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
08-22 12:12:54.109 11203-11244/com.powen_app E/OpenGLRenderer: allen debug liyu Key: 11
```

**Comment by wuxudong** [comment]
Your code works on my example project.

You can try example first.
