### ISSUE TITLE
androidjava.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference

### ISSUE THREAD

**Issue by wuyingtong** [wuxudong/react-native-charts-wrapper#150]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
                                                                     at com.github.mikephil.charting.renderer.PieChartRenderer.drawExtras(PieChartRenderer.java:638)
                                                                     at com.github.mikephil.charting.charts.PieChart.onDraw(PieChart.java:131)
                                                                     at android.view.View.draw(View.java:16178)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.View.draw(View.java:15948)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
                                                                     at android.view.View.draw(View.java:16181)
                                                                     at android.widget.ScrollView.draw(ScrollView.java:1712)
                                                                     at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:335)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15174)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3593)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3573)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:15134)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2615)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2434)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2067)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by wuxudong** [comment]
How to reproduce it?

**Comment by wuxudong** [comment]
It may be caused by PhilJay/MPAndroidChart#3470 .

**Comment by youngcao2015** [comment]
@wuxudong reply to "How to reproduce it?":  using PieChart inside a scrollview.
