### ISSUE TITLE
[Android] NoClassDefFoundError

### ISSUE THREAD

**Issue by Ble3k** [wuxudong/react-native-charts-wrapper#181]
Hi, I am getting this error while trying to run my app. App crashes and only android studio logs are available.

```
java.lang.NoClassDefFoundError: com.github.mikephil.charting.charts.Chart
                                                     at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                                     at java.lang.Class.getDexCacheType(Class.java:476)
                                                     at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166)
                                                     at java.lang.reflect.Method.getParameterTypes(Method.java:170)
                                                     at java.lang.Class.getDeclaredMethods(Class.java:673)
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:426)
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:320)
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:318)
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:318)
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:318)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:122)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:116)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:79)
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:66)
                                                     at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:205)
                                                     at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:146)
                                                     at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93)
                                                     at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:222)
                                                     at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:146)
                                                     at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:211)
                                                     at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:70)
                                                     at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:150)
                                                     at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:147)
                                                     at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81)
                                                     at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                                                     at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1191)
                                                     at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1161)
                                                     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1094)
                                                     at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112)
                                                     at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:922)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.mikephil.charting.charts.Chart" on path: DexPathList[[zip file "/data/app/com.binomysteryshopper-1/base.apk"],nativeLibraryDirectories=[/data/app/com.binomysteryshopper-1/lib/x86, /data/app/com.binomysteryshopper-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
                                                     at java.lang.Class.getDexCacheType(Class.java:476) 
                                                     at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:166) 
                                                     at java.lang.reflect.Method.getParameterTypes(Method.java:170) 
                                                     at java.lang.Class.getDeclaredMethods(Class.java:673) 
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:426) 
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:320) 
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:318) 
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:318) 
                                                     at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:318) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:122) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:116) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:79) 
                                                     at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:66) 
                                                     at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:205) 
                                                     at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:146) 
                                                     at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93) 
                                                     at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:222) 
                                                     at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:146) 
                                                     at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:211) 
                                                     at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:70) 
                                                     at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:150) 
                                                     at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:147) 
                                                     at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:81) 
                                                     at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                                                     at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1191) 
                                                     at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1161) 
                                                     at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1094) 
                                                     at com.facebook.react.ReactInstanceManager.access$800(ReactInstanceManager.java:112) 
                                                     at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:922) 
                                                     at java.lang.Thread.run(Thread.java:818) 
                                                 	Suppressed: java.lang.ClassNotFoundException: com.github.mikephil.charting.charts.Chart
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                 		at java.lang.ClassLoader.loadClass(ClassLoader.
```

react-native - 0.50
react-native-charts-wrapper - 0.4.1

Was linked as it said in docs.

**Comment by wuxudong** [comment]
Suppressed: java.lang.ClassNotFoundException: com.github.mikephil.charting.charts.Chart

MpAndroidChart is not added correctly.

**Comment by Ble3k** [comment]
How to add it correctly? I followed the steps in readme

**Comment by Ble3k** [comment]
```
del %appdata%\Temp\react-native-* & cd android & gradlew clean & cd .. & del node_modules/ & npm cache clean --force & npm install & npm start -- --reset-cache
```

This solved my issue, but on my mac I used rm -rf instead of def. Hope this will help someone, I spent 2 days on this shit.
