### ISSUE TITLE
android的报错data长度是-22

### ISSUE THREAD

**Issue by guoguoss** [wuxudong/react-native-charts-wrapper#239]
` this.setState(
            update(this.state, {
                xAxis:{
                    $set: {
                        textColor: processColor('white'),
                        // textSize: 16,
                        gridColor: processColor('#0B141D'),
                        gridLineWidth: 1,
                        axisLineColor: processColor('#223142'),
                        axisLineWidth: 1.5,
                        gridDashedLine: {
                            lineLength: 10,
                            spaceLength: 10
                        },
                        avoidFirstLastClipping: true,
                        position: 'BOTTOM'
                    }
                },
                yAxis: {
                    $set: {
                        left: {
                            drawGridLines: false,
                            // axisMaximum:50,
                            textColor: processColor('white'),
                            gridColor: processColor('#0B141D'),
                            axisLineColor:processColor('#223142'),
                            // axisMinimum:-20
                        },
                        right: {
                            enabled: false
                        }
                    }
                },
                data: {
                    $set: {
                        dataSets: [{
                            values:
                                [{"x":0,"y":25.0997},{"x":0,"y":24.0797},{"x":0,"y":23.20996},{"x":0,"y":22.296},{"x":0,"y":21.209436},{"x":0,"y":21.009497},{"x":0,"y":19.911},{"x":0,"y":9.9191},{"x":0,"y":9.8301},{"x":0,"y":9.801},{"x":0,"y":9.6881},{"x":0,"y":9.191},{"x":0,"y":9.1},{"x":0,"y":8.1},{"x":0,"y":7},{"x":0,"y":6},{"x":0,"y":5},{"x":0,"y":0.01}]
                            ,
                            label: 'Buy',
                            config: {
                                lineWidth: 2,
                                drawValues: false,
                                drawCircles: false,
                                highlightColor: processColor('red'),
                                color: processColor('#3DADD9'),
                                drawFilled: true,
                                fillColor: processColor('#3DADD9'),
                                fillAlpha: 30,
                                highlightEnabled: false,
                                // dashedLine: {
                                //   lineLength: 20,
                                //   spaceLength: 20
                                // }
                            }
                        }, {
                            values: 
                                 [{"x":0.226,"y":0.15},{"x":0.22,"y":0.151},{"x":0.2159,"y":0.486},{"x":0.2,"y":0.487},{"x":0.199,"y":0.6},{"x":0.191,"y":0.58866},{"x":0.181,"y":1.47412},{"x":0.179,"y":1.49661},{"x":0.17,"y":1.5442},{"x":0.168,"y":1.55769},{"x":0.1663,"y":1.95769},{"x":0.162,"y":2.05769},{"x":0.16,"y":2.07619},{"x":0.158,"y":3.33619}]
                            ,
                            label: 'Sell',
                            config: {
                                lineWidth: 1,
                                drawValues: false,
                                circleRadius: 5,
                                highlightEnabled: true,
                                drawHighlightIndicators: true,
                                color: processColor('#FF4B4B'),
                                drawFilled: true,
                                 valueTextSize:1,
                                fillColor: processColor('#FF4B4B'),
                                fillAlpha: 45,
                                valueFormatter: "###.0",
                                circleColor: processColor('#FF4B4B')
                            }
                        }],
                    }
                }
            })
        );
    }
    handleSelect(event) {
        let entry = event.nativeEvent
        if (entry == null) {
            this.setState({...this.state, selectedEntry: null})
        } else {
            this.setState({...this.state, selectedEntry: JSON.stringify(entry)})
        }

        console.log(event.nativeEvent)
    }
    render(){

        let borderColor = processColor("#223142");
        return (
            <View style={{flex: 1}}>

                {/*<View style={{height:80}}>*/}
                    {/*<Text> selected entry</Text>*/}
                    {/*<Text> {this.state.selectedEntry}</Text>*/}
                {/*</View>*/}

                <View style={styles.container}>

                    <LineChart
                        style={styles.chart}
                        data={this.state.data}
                        chartDescription={{text: ''}}
                        legend={this.state.legend}
                        marker={this.state.marker}

                        // drawGridBackground={true}

                         borderColor={borderColor}
                        borderWidth={1}
                        drawBorders={true}

                        touchEnabled={true}
                        dragEnabled={true}
                        scaleEnabled={true}
                        scaleXEnabled={true}
                        scaleYEnabled={true}
                        pinchZoom={true}
                        doubleTapToZoomEnabled={false}

                        dragDecelerationEnabled={true}
                        dragDecelerationFrictionCoef={0.99}
                        yAxis={this.state.yAxis}

                        keepPositionOnRotation={false}

                        xAxis={this.state.xAxis}

                        onSelect={this.handleSelect.bind(this)}
                        onChange={(event) => console.log(event.nativeEvent)}
                        chartBackgroundColor={processColor('#0B141D')}
                        ref="chart"
                    />
                </View>
            </View>

        );
    }`

android的错误如下：
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.nineeightproject, PID: 14145
                                                   java.lang.NegativeArraySizeException: -20
                                                       at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:178)
                                                       at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
                                                       at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
                                                       at android.view.View.draw(View.java:16245)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15242)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.draw(View.java:16248)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15242)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15237)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at android.view.View.draw(View.java:16248)
                                                       at android.widget.ScrollView.draw(ScrollView.java:1712)
                                                       at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:335)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15242)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.draw(View.java:16248)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15242)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15237)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15237)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.draw(View.java:16248)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15242)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15237)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15237)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3530)
                                                       at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:804)
                                                       at android.view.View.draw(View.java:16248)
                                                       at android.view.View.updateDisplayListIfDirty(View.java:15242)
                                                       at android.view.View.draw(View.java:16015)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3740)

**Comment by wuxudong** [comment]
Can you provide a reproduce project?

**Comment by wuxudong** [comment]
Close inactive issue. Reopen it if necessary.

**Comment by RajaganapathiPreludeSys** [comment]
I am facing the Same issue...

For static values as in the example https://github.com/wuxudong/react-native-charts-wrapper/blob/master/Example/app/LineChartGradientScreen.js

but for dynamic values I am getting the same issue
