### ISSUE TITLE
exception when I set animation property

### ISSUE THREAD

**Issue by L-Jovi** [wuxudong/react-native-charts-wrapper#24]
hi, thanks for your latest release, it's wonderful :)

I encounter below error when I set `animation` property, I find that native thread will crash while js side could still run.

![image](https://cloud.githubusercontent.com/assets/7262199/24441821/f79096a6-148d-11e7-9697-60f69aa883bf.png)

And if I remove `animation` property from my chart config object, all thing back to normal.

I try to figure out reason and have no idea, just provide my data config as below json format,

the first one is basic config before I fetch remote data, and the second one is fill data which be fetch from remote server.

would you mind take a look, I debug many times but cannot find any problem except the config possible.

---

__basic config before fill remote data__

[basic_config.txt](https://github.com/wuxudong/react-native-charts-wrapper/files/878767/basic_config.txt)

____fill remote data after http request____
[basic_config_with_filling_data.txt](https://github.com/wuxudong/react-native-charts-wrapper/files/878775/basic_config_with_filling_data.txt)

thanks for your time,

regards.

**Comment by wuxudong** [comment]
android or iOS?

**Comment by L-Jovi** [comment]
@wuxudong  thanks for your reply :)

both platform have animation problem if I enable it, and they refer to the same issue.

I'll paste log below.

thanks again.

__ios__

```
2017-03-29 18:53:37.184 [error][tid:main][RCTUIManager.m:1196] Error setting property 'animation' of RNBarChart with tag #1132: Exception thrown while executing UI block: *** +[NSJSONSerialization dataWithJSONObject:options:error:]: value parameter is nil
```

__android__

```
03-29 06:50:48.778 4649-4649/com.tapdb.analytics E/unknown:ViewManager: Error while updating prop animation
                                                                        java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:78)
                                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
                                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
                                                                            at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36)
                                                                            at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:125)
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:92)
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784)
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831)
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45)
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
                                                                            at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                            at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference
                                                                            at com.github.wuxudong.rncharts.utils.BridgeUtils.validate(BridgeUtils.java:10)
                                                                            at com.github.wuxudong.rncharts.charts.ChartBaseManager.setAnimation(ChartBaseManager.java:178)
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:78) 
                                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123) 
                                                                            at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42) 
                                                                            at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36) 
                                                                            at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:125) 
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:92) 
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784) 
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831) 
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45) 
                                                                            at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870) 
                                                                            at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                            at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131) 
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856) 
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:603) 
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
                                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
03-29 06:50:48.778 4649-4649/com.tapdb.analytics E/unknown:React: Exception in native call
                                                                  com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'animation' of a view managed by: RNBarChart
                                                                      at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:90)
                                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
                                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
                                                                      at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36)
                                                                      at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:125)
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:92)
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784)
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831)
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45)
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870)
                                                                      at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
                                                                      at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:78)
                                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123) 
                                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42) 
                                                                      at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36) 
                                                                      at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:125) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:92) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870) 
                                                                      at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                      at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131) 
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856) 
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:603) 
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference
                                                                      at com.github.wuxudong.rncharts.utils.BridgeUtils.validate(BridgeUtils.java:10)
                                                                      at com.github.wuxudong.rncharts.charts.ChartBaseManager.setAnimation(ChartBaseManager.java:178)
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:78) 
                                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123) 
                                                                      at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42) 
                                                                      at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36) 
                                                                      at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:125) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:92) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:784) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:831) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:45) 
                                                                      at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:870) 
                                                                      at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32) 
                                                                      at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131) 
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856) 
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670) 
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:603) 
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844) 
                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by wuxudong** [comment]
the exception stack trace indicates that the `animation` object you set is null.

have you reset `animation` after you fetch remote data?

**Comment by L-Jovi** [comment]
@wuxudong  thanks again for your reply :)

yes, some condition I need update my chart without animation, in order to implement it I use `lodash.unset(chartData, 'animation')` to remove `animation` key, it works before I migrate my project dependency to current smart wrapper chart project.

I follow your suggestion and fix my logic to
```
const newChartData = lodash.merge(chartData, {
  animation: {
    durationX: 0,
    durationY: 0,
  },
})
```

regards :)
