### ISSUE TITLE
Example build problem:  Unable to resolve module `react` 

### ISSUE THREAD

**Issue by alexsmartens** [wuxudong/react-native-charts-wrapper#240]
Hi, 
I'm having the following problem with building the react-native-charts-wrapper example:
```
Loading dependency graph, done.
Bundling `index.android.js`  [development, non-minified]  0.0% (1/589), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `react` from `C:\Users\Alex\Downloads\react-native-charts-wrapper\lib\BarChart.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ModuleResolver.resolveNodeDependency (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:292:11)
    at ModuleResolution.tryResolveSync (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:103:16)
    at Object.tryResolveSync (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:118:12)
    at ResolutionRequest.resolveDependency (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:100:39)
    at dependencyNames.map.name (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:134:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:133:42)
    at Promise.resolve.then (C:\Users\Alex\Downloads\react-native-charts-wrapper\Example\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:173:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```
Troubleshooting this problem I followed the proposed by the error handler 3 steps (also referenced in #159). This did not help. 
Any suggestions?

**Comment by wuxudong** [comment]
yarn start --reset-cache?

**Comment by jackmew** [comment]
I have the same problem. I follow all the step from the information including npm start --reset-cache. And I remove whole project and clone the react-native-charts-wrapper repo again. But it still the same.
![simulator screen shot - iphone x - 2018-04-10 at 10 54 31](https://user-images.githubusercontent.com/6193983/38535473-d1d7100e-3cad-11e8-99e6-96ffc1d5cae7.png)

**Comment by jackmew** [comment]
Just do npm install 2 times: 
1.react-native-charts-wrapper/
2.react-native-charts-wrapper/Example

Open react-native-charts-wrapper/Example/ios/Example.xcworkspace
Run

![screen shot 2018-04-17 at 3 34 11 pm](https://user-images.githubusercontent.com/6193983/38858007-df704c6a-4254-11e8-9187-798d1811d1f8.png)
