### ISSUE TITLE
Getting out of bounds exception when X zoom value above 15.

### ISSUE THREAD

**Issue by Lastin** [wuxudong/react-native-charts-wrapper#398]
```
09-19 10:16:16.730 24835 24835 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:437)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:96)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:263)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.draw(View.java:19192)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18142)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4220)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4200)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:18101)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
09-19 10:16:16.730 24835 24835 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-19 10:16:16.731 24835 24835 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-19 10:16:16.731 24835 24835 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-19 10:16:16.731 24835 24835 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-19 10:16:16.731 24835 24835 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
09-19 10:16:16.731 24835 24835 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
### Cause
happens in combined chart with toggleable options, in situation when data looks something like:
```
data = {
  data: {
    candleData: {
      dataSets: [{ values: [ {shadowH: 1...} ] }]
    },
    lineData: {
      dataSets: [{values: [], label: ""}]
    }
  }
}
```
Meaning we have at least 1 data point in candle data, and our lineData has some data set which has values with length smaller than the size of candle data sets.

Not sure if it applies for other mixtures of chart types.

### Workaround
Simple workaround works:
```
return {
      enabled: chartData.length > 0,
      legend: {
        enabled: false
      },
      xAxis: {
        drawLabels: true,
        drawGridLines: true,
        position: "BOTTOM",
        valueFormatter: chartData.map(item => item.dateStr)
      },
      yAxis: {
        left: {
          enabled: this.props.options.volume
        },
        right: {
          granularityEnabled: true,
          granularity: 10
        }
      },
      data: {
        lineData: {
          dataSets: Object.keys(this.props.options)
            .filter(key => this.props.options[key] && options[key])
            .map(this.getDataSet)
        },
        candleData: {
          dataSets: [
            {
              values: chartData,
              axisDependency: "right",
              label: "",
              config: {
                highlightColor: darkgray,
                shadowColor: black,
                shadowWidth: 1,
                shadowColorSameAsCandle: true,
                increasingColor: positiveGreen,
                increasingPaintStyle: "fill",
                decreasingColor: negativeRed
              }
            }
          ]
        },
        barData: this.getVolumeBarData()
      }
    };
```
Filter particularly avoids the issue in my case (where `this.props.options` is the boolean-only object):
```
Object.keys(this.props.options)
            .filter(key => this.props.options[key] && options[key])
            .map(this.getDataSet)
```
Maybe I should just post an issue on the MPAndroidCharts directly?

**Comment by wuxudong** [comment]
If you want to limit scale, you can also add 

visibleRange: {x: {min: 1}}

**Comment by Wangzihao5325** [comment]
visibleRange: {x: {min: 1}}

i just met the same exception. where i should add the 'visibleRange' ? i can't find visibleRange in api Doc.
