### ISSUE TITLE
App is crashing on Setting dataSet to null on LineChart(Android only)

### ISSUE THREAD

**Issue by manjuy124** [wuxudong/react-native-charts-wrapper#430]
at com.github.mikephil.charting.data.DataSet.getEntryForIndex(DataSet.java:286)
        at com.github.mikephil.charting.utils.Transformer.generateTransformedValuesLine(Transformer.java:184)
        at com.github.mikephil.charting.renderer.LineChartRenderer.drawValues(LineChartRenderer.java:547)
        at com.github.mikephil.charting.renderer.CombinedChartRenderer.drawValues(CombinedChartRenderer.java:96)
        at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:264)

I think issue is related to [this](https://github.com/hannesa2/MPAndroidChart/commit/502767e3f41d04aaf5f5ac1950ef8efdd3f060fc#diff-4de9ee187c6bb4635874230682bec866)  one. But how do we rectify in react

**Comment by manjuy124** [comment]
Can anyone help with this issue? Still the issue persist with our project in Android. On the other side, iO S is working fine.

**Comment by OneStromberg** [comment]
I have same issue.
Using graph for represent data by day, and some days could be empty, so I pass `null`. On iOS working like a charm, but Android just crushes.

**Comment by DealPete** [comment]
I also have this problem. I have a chart that draws a line chart from time series data. However, sometimes there is no data for the period that the user has selected, and trying to graph an empty data set causes to app to crash. It crashes consistently on Android, but I have seen the same behaviour on iOS.

The work around, of course, is to not show a graph when there is no data. It would be better, though, to have the library display some default graph in this case rather than crashing.

**Comment by wanxue0804** [comment]
+1
